### PR TITLE
Programmatic docs, OPEN DISCUSSION

### PR DESCRIPTION
**Pull request by andreaTP**
Please feel free to add any suggestion!

This is just an attempt ...

result can be seen here:
https://andreatp.github.io/scala-native-docs/docs/

WDYT?

### CODE REVIEW

**Comment by frgomes** [comment]
Hi Andrea, sorry for delay.

Yes! It looks pretty nice.
I've just found that there are strange fonts when verbatim code is shown, like bash command lines, for example.

I will merge it on my local workstation and play with it in order to have a better idea of what you did.
Talk to you later. :-)

**Comment by densh** [comment]
Here is my asymmetric response to that: https://github.com/scala-native/scala-native/pull/298

As discussed in the chat before, I'm am afraid that using a completely new documentation system is going to be less maintainable long-term compared to a well-established equivalent.

**Comment by frgomes** [comment]
@densh : Sphinx is really powerful, far more expressive than Markdown.

On the other hand, Scala Native should provide a Scala ecosystem for users and developers, as far as possible, IMHO. I don't see reason for adopting tools from Python and not from Haskell nor Erlang nor Lua nor any other random programming language. I see reason for adopting Scala over any other programming language.

**Comment by andreaTP** [comment]
I'm with you @frgomes .
But the owner of the project is @densh and his position is at least fair.

**Comment by densh** [comment]
If both sphinx and paradox where on the same level of support and feature completeness, the decision might have been different. But having used markdown dialects before for documentation on docs.scala-lang.org, I'd rather not make the same mistake again. Markdown was never meant as a language for documentation in the first place and it really falls apart on non-trivial multi-page projects.

**Pull request closed without merging**
